# Generated by Django 6.0.8 on 2026-09-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=300, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'Ежедневно'), (2, 'Раз в 2 дня'), (3, 'Раз в 3 дня'), (4, 'Раз в 4 дня'), (5, 'Раз в 5 дней'), (6, 'Раз в 6 дней'), (7, 'Раз в неделю')], default=1, verbose_name='Периодичность (дни)')),
                ('reward', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Время на выполнение (секунды)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_habits', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['id'],
            },
        ),
    ]
